:: This script will create MP3 files of each original song from the HD soundtrack (found on DVD)
:: http://www.amazon.com/Rise-Nations-Soundtrack-Brian-Reynolds/dp/B00009ZYBQ
:: You need VLC in order to run this script
:: Make sure the directory structure is in place before you try to run this script.
:: The directory structure is as follows: tracks\battle_defeat\ - tracks\battle_victory\ - tracks\economic\ - tracks\lose\ - tracks\win\

:: I read through these instructions to get create this batch file: https://wiki.videolan.org/Documentation:Streaming_HowTo_New/

vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\battle_victory\Galleons.wav}" dvd:///D:\#1:1-1:1 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\economic\Sri Lanka.wav}" dvd:///D:\#1:2-1:2 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\economic\Simple Song.wav}" dvd:///D:\#1:3-1:3 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\battle_defeat\Tribes.wav}" dvd:///D:\#1:4-1:4 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\economic\Brazil.wav}" dvd:///D:\#1:5-1:5 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\battle_defeat\Mist at Dawn.wav}" dvd:///D:\#1:6-1:6 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\battle_defeat\Battle at Witch Creek.wav}" dvd:///D:\#1:7-1:7 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\economic\Dark Forest.wav}" dvd:///D:\#1:8-1:8 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\battle_victory\Revolver.wav}" dvd:///D:\#1:9-1:9 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\economic\Wing and a Prayer.wav}" dvd:///D:\#1:10-1:10 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\battle_victory\High Strung.wav}" dvd:///D:\#1:11-1:11 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\battle_defeat\Desert Wind.wav}" dvd:///D:\#1:12-1:12 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\battle_defeat\Allerton.wav}" dvd:///D:\#1:13-1:13 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\battle_victory\The Russian.wav}" dvd:///D:\#1:14-1:14 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\economic\Eire.wav}" dvd:///D:\#1:15-1:15 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\economic\Gobi.wav}" dvd:///D:\#1:16-1:16 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\lose\Waterloo.wav}" dvd:///D:\#1:17-1:17 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\economic\Indochine.wav}" dvd:///D:\#1:18-1:18 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\economic\Morocco.wav}" dvd:///D:\#1:19-1:19 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\economic\Hearth.wav}" dvd:///D:\#1:20-1:20 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\economic\Santiago.wav}" dvd:///D:\#1:21-1:21 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\economic\Across the Bog.wav}" dvd:///D:\#1:22-1:22 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\battle_defeat\Osaka.wav}" dvd:///D:\#1:23-1:23 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\battle_victory\Attack.wav}" dvd:///D:\#1:24-1:24 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\battle_victory\William Wallace.wav}" dvd:///D:\#1:25-1:25 vlc://quit
vlc -I dummy --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout "#transcode{acodec=s16l,channels=2,samplerate=48000}:std{access=file,mux=wav,dst=tracks\win\Arc De Triomphe.wav}" dvd:///D:\#1:26-1:26 vlc://quit